# Generated by Django 4.2 on 2024-05-31 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_cards', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
