# Generated by Django 4.2 on 2024-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_tags_alter_card_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='cards.tag'),
        ),
    ]

"""
### Знакомимся с многими-ко-многим.

"""